blank_issues_enabled: false
contact_links:
  - name: SDKForge Community Support
    url: https://github.com/orgs/SDKForge/discussions
    about: Please ask and answer questions here.
  - name: SDK Documentation
    url: https://github.com/SDKForge/template-sdk#readme
    about: Check our documentation for answers.
  - name: Kotlin Multiplatform Resources
    url: https://kotlinlang.org/docs/multiplatform.html
    about: Learn more about Kotlin Multiplatform development.
