name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        
        Please provide detailed information to help us understand your request.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: A clear description of what problem this feature would solve
      placeholder: "I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear description of what you want to happen
      placeholder: "I would like to see..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear description of any alternative solutions you've considered
      placeholder: "I considered..."
  - type: dropdown
    id: platforms
    attributes:
      label: Target Platforms
      description: Which platforms should this feature support?
      multiple: true
      options:
        - "Android"
        - "iOS"
    validations:
      required: true
  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be valuable
      placeholder: "This would be useful when..."
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Critical - Essential for my use case"
        - "High - Important for my workflow"
        - "Medium - Nice to have"
        - "Low - Minor improvement"
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas about how this could be implemented?
      placeholder: "Optional: Share any technical implementation thoughts..."
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: "Any additional information that might help us understand your request"
